

all:

OPENFST_CXXFLAGS = 
OPENFST_LDLIBS =

include ../config.mk


# you can uncomment matrix-lib-speed-test if you want to do the speed tests.

TESTFILES =

OBJFILES = matrix.o vector.o matrix-functions.o compressed-matrix.o

LIBNAME = cpucompute

ADDLIBS = ../base/base.a

include ../makefiles/default_rules.mk

